// actionTypes.js
export const SET_USER = 'SET_USER';
export const SET_PROFILE_IMAGE = 'SET_PROFILE_IMAGE';
export const ADD_POSTED_PROPERTY = 'ADD_POSTED_PROPERTY';
export const REMOVE_POSTED_PROPERTY = 'REMOVE_POSTED_PROPERTY';
export const ADD_TOUR_REQUEST = 'ADD_TOUR_REQUEST';
export const REMOVE_TOUR_REQUEST = 'REMOVE_TOUR_REQUEST';
export const ADD_CONTACT_REQUEST = 'ADD_CONTACT_REQUEST';
export const REMOVE_CONTACT_REQUEST = 'REMOVE_CONTACT_REQUEST';
export const SET_TOUR_APPLIES = 'SET_TOUR_APPLIES';
export const SET_CONTACT_APPLIES = 'SET_CONTACT_APPLIES';
export const LOGOUT_USER = 'LOGOUT_USER';
