const Dymmy = [
    {
        "_id": {
            "$oid": "65f45c385047125886e3ffcb"
        },
        "id": 3,
        "uploadedBy": "Birju",
        "emailOfUploader": "birjumandal007@gmail.com",
        "contactOfUploader": "919832274114",
        "UpdateDate": {
            "$date": "2024-03-02T00:00:00.000Z"
        },
        "image_files": "https://mediagmp.s3.amazonaws.com/media/U12XVHHE4J.webp",
        "description": "very good commercial property",
        "Zone": "10",
        "Location": "New town",
        "PIN": 45678,
        "State": "West Bengal",
        "Type": "Commercial",
        "Area": 10,
        "Rent": 100000,
        "BedRoom": 2,
        "BathRoom": 3,
        "ServantQuarter": "yes",
        "Securitydeposit": 20000,
        "Brokerage": 10000,
        "FLOOR": 5,
        "Furnishing": "yes",
        "Flooring": "no",
        "CarParking": "yes",
        "BikeParking": "yes",
        "CycleParking": "yes",
        "Facing": "south",
        "FlatView": "good",
        "Age": 2,
        "Nature": "good",
        "Lift": "yes",
        "WaterAvailability": "yes",
        "PetFriendly": "no",
        "Laundry": "yes",
        "Dishwasher": "yes",
        "WashingMachine": null,
        "ChimneyProvision": null,
        "WaterFilterProvision": "yes",
        "HobProvision": null,
        "MicrowaveProvision": null,
        "Fridge": "yes",
        "TV": null,
        "AC": null,
        "Balcony": null,
        "Gym": null,
        "SwimmingPool": null,
        "ClubHouse": null,
        "Security": null,
        "MetroStation": null,
        "BusStation": null,
        "AutoStand": null,
        "RailwayStation": null,
        "School": null,
        "Hospital": null,
        "ChildrenPark": null,
        "RestaurantsCafes": null,
        "ShoppingMall": null,
        "CinemaHall": null,
        "location": {
            "type": "Point",
            "coordinates": [
                88.47979029999999,
                22.5753931
            ]
        }
    },
    {
        "_id": {
            "$oid": "65f45e875047125886e3ffce"
        },
        "id": 4,
        "uploadedBy": "Akash Ranjan Mandal",
        "emailOfUploader": "akashranjanmandal@gmail.com",
        "contactOfUploader": "917319292532",
        "UpdateDate": {
            "$date": "2024-03-15T00:00:00.000Z"
        },
        "image_files": "https://mediagmp.s3.amazonaws.com/media/CAKIT33IM5.webp",
        "description": "Best Property in Behala",
        "Zone": "South Kolkata",
        "Location": "Rajarhat",
        "PIN": 700008,
        "State": "West Bengal",
        "Type": "Commercial",
        "Area": 1500,
        "Rent": 30000,
        "BedRoom": 0,
        "BathRoom": 0,
        "ServantQuarter": "No",
        "Securitydeposit": 30000,
        "Brokerage": 15000,
        "FLOOR": 2,
        "Furnishing": "Full",
        "Flooring": "Marble",
        "CarParking": "Yes",
        "BikeParking": "Yes",
        "CycleParking": "No",
        "Facing": "Road",
        "FlatView": "South",
        "Age": 1,
        "Nature": "Holy",
        "Lift": "Yes",
        "WaterAvailability": "2 Hours",
        "PetFriendly": "No",
        "Laundry": "No",
        "Dishwasher": "No",
        "WashingMachine": null,
        "ChimneyProvision": null,
        "WaterFilterProvision": null,
        "HobProvision": null,
        "MicrowaveProvision": null,
        "Fridge": null,
        "TV": null,
        "AC": "Yes",
        "Balcony": "Yes",
        "Gym": null,
        "SwimmingPool": null,
        "ClubHouse": null,
        "Security": null,
        "MetroStation": null,
        "BusStation": null,
        "AutoStand": null,
        "RailwayStation": null,
        "School": null,
        "Hospital": null,
        "ChildrenPark": null,
        "RestaurantsCafes": null,
        "ShoppingMall": null,
        "CinemaHall": null,
        "location": {
            "type": "Point",
            "coordinates": [
                88.3136044,
                22.4866812
            ]
        }
    },
    {
        "_id": {
            "$oid": "65f73b1d8897fbf73f205b02"
        },
        "id": 5,
        "uploadedBy": "Subhajit Paul",
        "emailOfUploader": "paulsubhajit78242548@gmail.com",
        "contactOfUploader": "918420344070",
        "UpdateDate": {
            "$date": "2024-03-01T00:00:00.000Z"
        },
        "image_files": "https://mediagmp.s3.amazonaws.com/media/X65WX0LL9S.webp",
        "description": "Hot Property Near New Garia",
        "Zone": "South Kolkata",
        "Location": "New Town",
        "PIN": 700020,
        "State": "West Bengal",
        "Type": "Residential",
        "Area": 1490,
        "Rent": 19000,
        "BedRoom": 4,
        "BathRoom": 3,
        "ServantQuarter": "Yes",
        "Securitydeposit": 38000,
        "Brokerage": 19000,
        "FLOOR": 4,
        "Furnishing": "Full",
        "Flooring": "Tiles",
        "CarParking": "Yes",
        "BikeParking": "Yes",
        "CycleParking": "Yes",
        "Facing": "Main Road",
        "FlatView": "South East",
        "Age": 1,
        "Nature": "Housing Complex",
        "Lift": "Yes",
        "WaterAvailability": "24 Hours",
        "PetFriendly": "Yes",
        "Laundry": null,
        "Dishwasher": null,
        "WashingMachine": null,
        "ChimneyProvision": "Yes",
        "WaterFilterProvision": null,
        "HobProvision": null,
        "MicrowaveProvision": null,
        "Fridge": null,
        "TV": null,
        "AC": null,
        "Balcony": null,
        "Gym": null,
        "SwimmingPool": null,
        "ClubHouse": null,
        "Security": null,
        "MetroStation": null,
        "BusStation": null,
        "AutoStand": null,
        "RailwayStation": null,
        "School": null,
        "Hospital": null,
        "ChildrenPark": null,
        "RestaurantsCafes": null,
        "ShoppingMall": null,
        "CinemaHall": null,
        "location": {
            "type": "Point",
            "coordinates": [
                88.3961473,
                22.4696435
            ]
        }
    }
]


const BASE_URL = "http://192.168.160.104:8080/api/"
module.exports = {
    BASE_URL: BASE_URL,
    Dymmy: Dymmy
}